# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'
# ignore all warnings from all pods
inhibit_all_warnings!

target 'Pino-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Pino-iOS
  pod 'TrustWalletCore'
  pod 'Charts'

  target 'Pino-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Pino-iOSUITests' do
    # Pods for testing
  end
  
end
