# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pino-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # ignore all warnings from all pods
  inhibit_all_warnings!
  
  # Pods for Pino-iOS
  # Firebase Pods
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'

  target 'Pino-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Pino-iOSUITests' do
    # Pods for testing
  end

end
