-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgZrXiknAW5DHUDTKW
2Nqcav37fOwLdqdckFNxlUWipsSgCgYIKoZIzj0DAQehRANCAARRlFAZs+ftIsLz
gd6UzS3d3/WfgsfBCsVXsrRrDd07hzdZOcfn2hbEliufcMwkyoELHGVABw9AMhQ4
ZDgQdqs9
-----END PRIVATE KEY-----