default_platform(:ios)

platform :ios do

  lane :run_ui_tests do
    cocoapods(use_bundle_exec: false)
    scan(
      workspace: "Pino-iOS.xcworkspace",
      scheme: "Pino-iOSUITests",
      device: "iPhone 14",
      clean: false
    )
  end

  lane :run_unit_tests do
    cocoapods(use_bundle_exec: false)
    scan(
      workspace: "Pino-iOS.xcworkspace",
      scheme: "Pino-iOSTests",
      device: "iPhone 14",
      clean: false
    )
  end

  desc "Get certificates"
  lane :certificates do
    match(
      type: "development",
      force_for_new_devices: true,
      readonly: true
    )

    match(
      type: "appstore",
      readonly: true
    )
  end

  desc "Generate new certificates"
  lane :generate_certs do
    match(
      type: "development",
      force_for_new_devices: true,
      readonly: false
    )

    match(
      type: "appstore",
      force_for_new_devices: true,
      readonly: false
    )
  end

  

end
