default_platform(:ios)

platform :ios do
  
  before_each do |lane, options|
    swiftformat(
      swiftversion: "5.5",                               # Specify swift version (optional)
      config: "../Pino-iOS/.swiftformat",                # Path to configuration file (optional)
      dryrun: false,                                     # Run in dry mode (without actually changing any files) (optional)
    )
    begin
      ensure_git_status_clean
    rescue
      commitMsg  = prompt(text: "Message: ")
      git_add()
      git_commit(path:"*", message: commitMsg)
    end
  end

  lane :get_dev_certs do
    cert(development: true)
    sigh(development: true)
  end

  lane :checkout do
    branchName = prompt(text: "Branch Name: ")
    git_switch_branch(branch: branchName)
  end

  lane :push do
    scan(
      workspace: "Pino-iOS.xcworkspace",
      scheme: "Pino-iOSTests"
    )
    push_to_git_remote
  end
  
  lane :testflight_beta do
    changelog = prompt(text: "What to Test: ")
    xcodegen
    cocoapods(use_bundle_exec: false)
    xcbuild
    scan(
      workspace: "Pino-iOS.xcworkspace",
      scheme: "Pino-iOSTests"
    )
    upload_to_testflight(
      beta_app_feedback_email: "email@email.com",
      beta_app_description: "Pino is a crypto wallet app for iOS devices.",
      demo_account_required: false,
      notify_external_testers: true,
      changelog: changelog,
      username: "eskandari.sobhan@gmail.com",
      app_identifier: "com.krausefx.app",
      api_key: ""
    )
  end

end
